import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
// 侧边栏由文件系统自动生成：
// - 顺序由各文档 front matter 的 sidebar_position 和目录下的 _category_.json position 控制。
// - 分类标签、排序、landing 页由各目录的 _category_.json 控制。
// 新增文档放进 docs/ 对应目录即可自动出现在侧边栏，无需在此手动登记。
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
