/* Generated by tools/example-actions/pull-shared-action.mjs — do not edit. */
import type {ProgramVar, StepWire} from './types';
import ex0 from '@site/data/step-render/examples/05d33931-477a-4c18-a917-08d7b30d7779.json';
import ex1 from '@site/data/step-render/examples/0c8ab8ca-b721-407a-11da-08dc5ee89ca7.json';
import ex2 from '@site/data/step-render/examples/0cf96600-866a-4eac-7f44-08d8fe1fe745.json';
import ex3 from '@site/data/step-render/examples/0e698f4e-04ac-426d-b3eb-08d6c3be0bea.json';
import ex4 from '@site/data/step-render/examples/16317b5d-ffdf-4193-a919-08d7b30d7779.json';
import ex5 from '@site/data/step-render/examples/16cd6907-13d1-45bb-9c56-08d9f836c603.json';
import ex6 from '@site/data/step-render/examples/186c9f3f-46d4-4f63-00b9-08db56e12efe.json';
import ex7 from '@site/data/step-render/examples/18fdf83e-048e-46c7-185a-08d69d1d124b.json';
import ex8 from '@site/data/step-render/examples/1a7f485b-bf5d-42f4-6452-08d8ba8b34b3.json';
import ex9 from '@site/data/step-render/examples/1aefbbd1-cca2-42e6-c4e0-08d7f7cf8b53.json';
import ex10 from '@site/data/step-render/examples/1bdedee6-4774-42d3-7697-08d950c2afd2.json';
import ex11 from '@site/data/step-render/examples/20d89403-3c40-480d-394f-08d98bd92463.json';
import ex12 from '@site/data/step-render/examples/2214ddb5-d718-4da5-2c60-08d6c8ffb643.json';
import ex13 from '@site/data/step-render/examples/2376e6a5-b5d9-4afb-7655-08d950c2afd2.json';
import ex14 from '@site/data/step-render/examples/27d4c30d-803e-473e-4296-08da08643be0.json';
import ex15 from '@site/data/step-render/examples/2a59718b-523b-4e7e-a4a8-08d70bf0ab12.json';
import ex16 from '@site/data/step-render/examples/2a89f753-546d-45d0-bfd9-08d6720e1a02.json';
import ex17 from '@site/data/step-render/examples/2de554cd-f7f6-417c-6b7c-08da4f3f8574.json';
import ex18 from '@site/data/step-render/examples/2ee54fa9-ad5b-4273-6f9b-08db22290442.json';
import ex19 from '@site/data/step-render/examples/318b29ef-4bba-4d0c-a918-08d7b30d7779.json';
import ex20 from '@site/data/step-render/examples/345b395f-8f0a-4f35-a01f-08d7636fd69a.json';
import ex21 from '@site/data/step-render/examples/3737b0c5-e216-4f76-b13e-08dac77c5292.json';
import ex22 from '@site/data/step-render/examples/3b4e1cbc-9fbc-4686-764f-08d950c2afd2.json';
import ex23 from '@site/data/step-render/examples/3d9f7fbb-752a-40f5-d827-08d86cbb0005.json';
import ex24 from '@site/data/step-render/examples/3dfd19f5-7e33-4864-5286-08da4e691004.json';
import ex25 from '@site/data/step-render/examples/3eba3790-6c37-41c7-7aff-08d9bf67e5c4.json';
import ex26 from '@site/data/step-render/examples/3fc97b7e-7be1-4a23-3d64-08db3e27302e.json';
import ex27 from '@site/data/step-render/examples/456c2ade-5d5c-4096-a96c-08d7296fb043.json';
import ex28 from '@site/data/step-render/examples/45a0cf34-ca99-494c-4af7-08db410cf70d.json';
import ex29 from '@site/data/step-render/examples/4943c94a-0437-4b98-20f1-08d742f11f76.json';
import ex30 from '@site/data/step-render/examples/4aaaaf6c-1883-4c3a-9ed6-08d85d9ed340.json';
import ex31 from '@site/data/step-render/examples/4d774256-f3fa-4c61-72c6-08dac59559d0.json';
import ex32 from '@site/data/step-render/examples/4e40c634-8eca-4515-6b7e-08da4f3f8574.json';
import ex33 from '@site/data/step-render/examples/4f27bd92-e6fc-4c48-ad58-08dd15875f2b.json';
import ex34 from '@site/data/step-render/examples/52e0112f-076d-4347-df18-08d9db64e6a1.json';
import ex35 from '@site/data/step-render/examples/531248a5-f5ac-4ae5-75bd-08d709af9122.json';
import ex36 from '@site/data/step-render/examples/531dc01c-4b59-42ef-6fbc-08db22290442.json';
import ex37 from '@site/data/step-render/examples/55c2a301-191e-4650-aa19-08d743b351f9.json';
import ex38 from '@site/data/step-render/examples/56fba2f1-898e-403a-6b87-08da4f3f8574.json';
import ex39 from '@site/data/step-render/examples/582c20af-30ec-423d-b6ce-08db782fe3a2.json';
import ex40 from '@site/data/step-render/examples/5d5f0aa4-29fd-4db3-5f2a-08da0ff5530e.json';
import ex41 from '@site/data/step-render/examples/63e550e1-aa9f-478e-f824-08da38cccadf.json';
import ex42 from '@site/data/step-render/examples/65a5ee04-29bc-42f0-3962-08db5c50a3af.json';
import ex43 from '@site/data/step-render/examples/6aaceddc-6917-41cf-721a-08d697a27161.json';
import ex44 from '@site/data/step-render/examples/77cf03c8-7940-4ca1-82c4-08d9a96a6ccf.json';
import ex45 from '@site/data/step-render/examples/789bfd8d-3ef0-43c9-7f48-08d8fe1fe745.json';
import ex46 from '@site/data/step-render/examples/78e28478-b1ea-421e-75d3-08d692da05cc.json';
import ex47 from '@site/data/step-render/examples/7a49ca6b-d243-4478-1e87-08d9f1ba2358.json';
import ex48 from '@site/data/step-render/examples/7d6dcc8c-2a1f-41d3-35e5-08d95890efa9.json';
import ex49 from '@site/data/step-render/examples/7e0ffda7-cbc9-4e31-2462-08da4d582a20.json';
import ex50 from '@site/data/step-render/examples/80427a4f-78c4-4fc5-7b1a-08d6a9169e61.json';
import ex51 from '@site/data/step-render/examples/80dae94c-de3c-4a50-dbe6-08d7053e26bb.json';
import ex52 from '@site/data/step-render/examples/8139f36b-059a-49a6-9f64-08d8ff04bb1d.json';
import ex53 from '@site/data/step-render/examples/82678afc-219e-4e63-a7d1-08dd5143284a.json';
import ex54 from '@site/data/step-render/examples/837633b1-cbea-4156-0c36-08da45d22d56.json';
import ex55 from '@site/data/step-render/examples/840b5f51-e57c-4141-a270-08dc0740f11f.json';
import ex56 from '@site/data/step-render/examples/85e2fa76-4bfb-4e1b-aa78-08d80d33b91a.json';
import ex57 from '@site/data/step-render/examples/85f82b64-b24c-4e46-ba2c-08d6db3483c9.json';
import ex58 from '@site/data/step-render/examples/862a746e-35d8-4d6f-3efe-08d97ef43193.json';
import ex59 from '@site/data/step-render/examples/8ad1e7b0-5ce8-4d57-fa45-08dcdc2c1d1a.json';
import ex60 from '@site/data/step-render/examples/8af98895-ef82-46d1-dbe7-08d7053e26bb.json';
import ex61 from '@site/data/step-render/examples/8e49c374-062d-4824-979c-08db3d4a9dcd.json';
import ex62 from '@site/data/step-render/examples/9205705f-d1a7-4713-3d38-08d673be1748.json';
import ex63 from '@site/data/step-render/examples/9a2970fd-14a5-4428-9b2a-08d852fc39cc.json';
import ex64 from '@site/data/step-render/examples/9bfc34fb-b7f7-40bd-6d0c-08d6c304e16e.json';
import ex65 from '@site/data/step-render/examples/9fdf152f-dd42-482e-767a-08d950c2afd2.json';
import ex66 from '@site/data/step-render/examples/a10d3f7c-6eca-4a4e-16a8-08dd656169a1.json';
import ex67 from '@site/data/step-render/examples/a2933deb-ebe7-4895-69d4-08d992b19cae.json';
import ex68 from '@site/data/step-render/examples/a46e9573-1e4e-4e11-e93f-08d82eb96b41.json';
import ex69 from '@site/data/step-render/examples/a6aaa916-9fea-4355-fbd4-08d7cd418588.json';
import ex70 from '@site/data/step-render/examples/aa38d2b9-f95b-4a91-d713-08d827485760.json';
import ex71 from '@site/data/step-render/examples/abf666ed-08bc-46a9-6d8a-08d6bfa4ff29.json';
import ex72 from '@site/data/step-render/examples/acd50dea-9df0-4ed6-a3cf-08d7c216a695.json';
import ex73 from '@site/data/step-render/examples/acdba4d6-1c7a-4546-a11f-08d92725bcba.json';
import ex74 from '@site/data/step-render/examples/acf2fc09-3753-4b67-d714-08d827485760.json';
import ex75 from '@site/data/step-render/examples/b1c9e1a0-bb9a-41ad-6798-08d67448baf3.json';
import ex76 from '@site/data/step-render/examples/b20f2a88-3bc4-4446-fe0c-08db67a6796c.json';
import ex77 from '@site/data/step-render/examples/b3c33c64-efd2-4999-0c74-08d7249f7b58.json';
import ex78 from '@site/data/step-render/examples/b6098426-6fda-4db9-6d88-08d6bfa4ff29.json';
import ex79 from '@site/data/step-render/examples/b7a369da-ec8e-4d0f-764b-08d950c2afd2.json';
import ex80 from '@site/data/step-render/examples/b89f2926-96a1-4c81-fad4-08d9f7308243.json';
import ex81 from '@site/data/step-render/examples/bb16cf76-5b79-4327-4cdf-08da16aad73c.json';
import ex82 from '@site/data/step-render/examples/bbf0a162-6f95-46fb-1e7a-08dbbf546dec.json';
import ex83 from '@site/data/step-render/examples/bf4e796f-e1a5-41ba-1925-08d7b02d7fd4.json';
import ex84 from '@site/data/step-render/examples/c6da399c-c64f-468a-6d89-08d6bfa4ff29.json';
import ex85 from '@site/data/step-render/examples/d0464310-2558-4595-75ba-08d709af9122.json';
import ex86 from '@site/data/step-render/examples/d08bf039-e016-4482-7fe6-08dbdfe824d8.json';
import ex87 from '@site/data/step-render/examples/d197881b-f8c5-4ce9-a982-08d8f2798c37.json';
import ex88 from '@site/data/step-render/examples/d4eab7c4-b53e-4fd9-7f4a-08d8fe1fe745.json';
import ex89 from '@site/data/step-render/examples/d5470b3f-cae1-4388-75b8-08d709af9122.json';
import ex90 from '@site/data/step-render/examples/d59d0507-ad21-4783-a83a-08d6d0f9e36e.json';
import ex91 from '@site/data/step-render/examples/d9eb6be1-6185-4d6e-8459-08db738638c3.json';
import ex92 from '@site/data/step-render/examples/dd277f4e-50a4-4971-26fc-08d697a0f29b.json';
import ex93 from '@site/data/step-render/examples/dd32199e-8d36-465a-b13d-08dac77c5292.json';
import ex94 from '@site/data/step-render/examples/e4ec073a-1f86-449c-8001-08da66cce8dc.json';
import ex95 from '@site/data/step-render/examples/ea84295f-a89f-4eed-2181-08d87f35f7db.json';
import ex96 from '@site/data/step-render/examples/ef1a10ef-bbb2-4dcf-5f17-08d6cebc3090.json';
import ex97 from '@site/data/step-render/examples/efa8a4af-4a87-4d52-d718-08d827485760.json';
import ex98 from '@site/data/step-render/examples/f28447de-e525-440e-5f9b-08d67b52833a.json';
import ex99 from '@site/data/step-render/examples/f6fc9c05-7b95-40f7-b326-08d6756598a8.json';
import ex100 from '@site/data/step-render/examples/f757e64d-dff9-4bc1-6b82-08da4f3f8574.json';
import ex101 from '@site/data/step-render/examples/fa6ce878-59d6-4c9a-06b4-08db4d58400e.json';
import ex102 from '@site/data/step-render/examples/fb351711-0941-4816-d9b7-08db2ba80230.json';
import ex103 from '@site/data/step-render/examples/fe04a515-508b-4238-645d-08d8ba8b34b3.json';
import ex104 from '@site/data/step-render/examples/ff3309da-7c30-4655-6b7d-08da4f3f8574.json';

export type ExampleAction = {
  code: string;
  title: string;
  description?: string;
  author?: string;
  revision?: number;
  source: string;
  pulledAt?: string;
  variables?: ProgramVar[];
  steps: StepWire[];
};

const EXAMPLES: Record<string, ExampleAction> = {
  '05d33931-477a-4c18-a917-08d7b30d7779': ex0 as unknown as ExampleAction,
  '0c8ab8ca-b721-407a-11da-08dc5ee89ca7': ex1 as unknown as ExampleAction,
  '0cf96600-866a-4eac-7f44-08d8fe1fe745': ex2 as unknown as ExampleAction,
  '0e698f4e-04ac-426d-b3eb-08d6c3be0bea': ex3 as unknown as ExampleAction,
  '16317b5d-ffdf-4193-a919-08d7b30d7779': ex4 as unknown as ExampleAction,
  '16cd6907-13d1-45bb-9c56-08d9f836c603': ex5 as unknown as ExampleAction,
  '186c9f3f-46d4-4f63-00b9-08db56e12efe': ex6 as unknown as ExampleAction,
  '18fdf83e-048e-46c7-185a-08d69d1d124b': ex7 as unknown as ExampleAction,
  '1a7f485b-bf5d-42f4-6452-08d8ba8b34b3': ex8 as unknown as ExampleAction,
  '1aefbbd1-cca2-42e6-c4e0-08d7f7cf8b53': ex9 as unknown as ExampleAction,
  '1bdedee6-4774-42d3-7697-08d950c2afd2': ex10 as unknown as ExampleAction,
  '20d89403-3c40-480d-394f-08d98bd92463': ex11 as unknown as ExampleAction,
  '2214ddb5-d718-4da5-2c60-08d6c8ffb643': ex12 as unknown as ExampleAction,
  '2376e6a5-b5d9-4afb-7655-08d950c2afd2': ex13 as unknown as ExampleAction,
  '27d4c30d-803e-473e-4296-08da08643be0': ex14 as unknown as ExampleAction,
  '2a59718b-523b-4e7e-a4a8-08d70bf0ab12': ex15 as unknown as ExampleAction,
  '2a89f753-546d-45d0-bfd9-08d6720e1a02': ex16 as unknown as ExampleAction,
  '2de554cd-f7f6-417c-6b7c-08da4f3f8574': ex17 as unknown as ExampleAction,
  '2ee54fa9-ad5b-4273-6f9b-08db22290442': ex18 as unknown as ExampleAction,
  '318b29ef-4bba-4d0c-a918-08d7b30d7779': ex19 as unknown as ExampleAction,
  '345b395f-8f0a-4f35-a01f-08d7636fd69a': ex20 as unknown as ExampleAction,
  '3737b0c5-e216-4f76-b13e-08dac77c5292': ex21 as unknown as ExampleAction,
  '3b4e1cbc-9fbc-4686-764f-08d950c2afd2': ex22 as unknown as ExampleAction,
  '3d9f7fbb-752a-40f5-d827-08d86cbb0005': ex23 as unknown as ExampleAction,
  '3dfd19f5-7e33-4864-5286-08da4e691004': ex24 as unknown as ExampleAction,
  '3eba3790-6c37-41c7-7aff-08d9bf67e5c4': ex25 as unknown as ExampleAction,
  '3fc97b7e-7be1-4a23-3d64-08db3e27302e': ex26 as unknown as ExampleAction,
  '456c2ade-5d5c-4096-a96c-08d7296fb043': ex27 as unknown as ExampleAction,
  '45a0cf34-ca99-494c-4af7-08db410cf70d': ex28 as unknown as ExampleAction,
  '4943c94a-0437-4b98-20f1-08d742f11f76': ex29 as unknown as ExampleAction,
  '4aaaaf6c-1883-4c3a-9ed6-08d85d9ed340': ex30 as unknown as ExampleAction,
  '4d774256-f3fa-4c61-72c6-08dac59559d0': ex31 as unknown as ExampleAction,
  '4e40c634-8eca-4515-6b7e-08da4f3f8574': ex32 as unknown as ExampleAction,
  '4f27bd92-e6fc-4c48-ad58-08dd15875f2b': ex33 as unknown as ExampleAction,
  '52e0112f-076d-4347-df18-08d9db64e6a1': ex34 as unknown as ExampleAction,
  '531248a5-f5ac-4ae5-75bd-08d709af9122': ex35 as unknown as ExampleAction,
  '531dc01c-4b59-42ef-6fbc-08db22290442': ex36 as unknown as ExampleAction,
  '55c2a301-191e-4650-aa19-08d743b351f9': ex37 as unknown as ExampleAction,
  '56fba2f1-898e-403a-6b87-08da4f3f8574': ex38 as unknown as ExampleAction,
  '582c20af-30ec-423d-b6ce-08db782fe3a2': ex39 as unknown as ExampleAction,
  '5d5f0aa4-29fd-4db3-5f2a-08da0ff5530e': ex40 as unknown as ExampleAction,
  '63e550e1-aa9f-478e-f824-08da38cccadf': ex41 as unknown as ExampleAction,
  '65a5ee04-29bc-42f0-3962-08db5c50a3af': ex42 as unknown as ExampleAction,
  '6aaceddc-6917-41cf-721a-08d697a27161': ex43 as unknown as ExampleAction,
  '77cf03c8-7940-4ca1-82c4-08d9a96a6ccf': ex44 as unknown as ExampleAction,
  '789bfd8d-3ef0-43c9-7f48-08d8fe1fe745': ex45 as unknown as ExampleAction,
  '78e28478-b1ea-421e-75d3-08d692da05cc': ex46 as unknown as ExampleAction,
  '7a49ca6b-d243-4478-1e87-08d9f1ba2358': ex47 as unknown as ExampleAction,
  '7d6dcc8c-2a1f-41d3-35e5-08d95890efa9': ex48 as unknown as ExampleAction,
  '7e0ffda7-cbc9-4e31-2462-08da4d582a20': ex49 as unknown as ExampleAction,
  '80427a4f-78c4-4fc5-7b1a-08d6a9169e61': ex50 as unknown as ExampleAction,
  '80dae94c-de3c-4a50-dbe6-08d7053e26bb': ex51 as unknown as ExampleAction,
  '8139f36b-059a-49a6-9f64-08d8ff04bb1d': ex52 as unknown as ExampleAction,
  '82678afc-219e-4e63-a7d1-08dd5143284a': ex53 as unknown as ExampleAction,
  '837633b1-cbea-4156-0c36-08da45d22d56': ex54 as unknown as ExampleAction,
  '840b5f51-e57c-4141-a270-08dc0740f11f': ex55 as unknown as ExampleAction,
  '85e2fa76-4bfb-4e1b-aa78-08d80d33b91a': ex56 as unknown as ExampleAction,
  '85f82b64-b24c-4e46-ba2c-08d6db3483c9': ex57 as unknown as ExampleAction,
  '862a746e-35d8-4d6f-3efe-08d97ef43193': ex58 as unknown as ExampleAction,
  '8ad1e7b0-5ce8-4d57-fa45-08dcdc2c1d1a': ex59 as unknown as ExampleAction,
  '8af98895-ef82-46d1-dbe7-08d7053e26bb': ex60 as unknown as ExampleAction,
  '8e49c374-062d-4824-979c-08db3d4a9dcd': ex61 as unknown as ExampleAction,
  '9205705f-d1a7-4713-3d38-08d673be1748': ex62 as unknown as ExampleAction,
  '9a2970fd-14a5-4428-9b2a-08d852fc39cc': ex63 as unknown as ExampleAction,
  '9bfc34fb-b7f7-40bd-6d0c-08d6c304e16e': ex64 as unknown as ExampleAction,
  '9fdf152f-dd42-482e-767a-08d950c2afd2': ex65 as unknown as ExampleAction,
  'a10d3f7c-6eca-4a4e-16a8-08dd656169a1': ex66 as unknown as ExampleAction,
  'a2933deb-ebe7-4895-69d4-08d992b19cae': ex67 as unknown as ExampleAction,
  'a46e9573-1e4e-4e11-e93f-08d82eb96b41': ex68 as unknown as ExampleAction,
  'a6aaa916-9fea-4355-fbd4-08d7cd418588': ex69 as unknown as ExampleAction,
  'aa38d2b9-f95b-4a91-d713-08d827485760': ex70 as unknown as ExampleAction,
  'abf666ed-08bc-46a9-6d8a-08d6bfa4ff29': ex71 as unknown as ExampleAction,
  'acd50dea-9df0-4ed6-a3cf-08d7c216a695': ex72 as unknown as ExampleAction,
  'acdba4d6-1c7a-4546-a11f-08d92725bcba': ex73 as unknown as ExampleAction,
  'acf2fc09-3753-4b67-d714-08d827485760': ex74 as unknown as ExampleAction,
  'b1c9e1a0-bb9a-41ad-6798-08d67448baf3': ex75 as unknown as ExampleAction,
  'b20f2a88-3bc4-4446-fe0c-08db67a6796c': ex76 as unknown as ExampleAction,
  'b3c33c64-efd2-4999-0c74-08d7249f7b58': ex77 as unknown as ExampleAction,
  'b6098426-6fda-4db9-6d88-08d6bfa4ff29': ex78 as unknown as ExampleAction,
  'b7a369da-ec8e-4d0f-764b-08d950c2afd2': ex79 as unknown as ExampleAction,
  'b89f2926-96a1-4c81-fad4-08d9f7308243': ex80 as unknown as ExampleAction,
  'bb16cf76-5b79-4327-4cdf-08da16aad73c': ex81 as unknown as ExampleAction,
  'bbf0a162-6f95-46fb-1e7a-08dbbf546dec': ex82 as unknown as ExampleAction,
  'bf4e796f-e1a5-41ba-1925-08d7b02d7fd4': ex83 as unknown as ExampleAction,
  'c6da399c-c64f-468a-6d89-08d6bfa4ff29': ex84 as unknown as ExampleAction,
  'd0464310-2558-4595-75ba-08d709af9122': ex85 as unknown as ExampleAction,
  'd08bf039-e016-4482-7fe6-08dbdfe824d8': ex86 as unknown as ExampleAction,
  'd197881b-f8c5-4ce9-a982-08d8f2798c37': ex87 as unknown as ExampleAction,
  'd4eab7c4-b53e-4fd9-7f4a-08d8fe1fe745': ex88 as unknown as ExampleAction,
  'd5470b3f-cae1-4388-75b8-08d709af9122': ex89 as unknown as ExampleAction,
  'd59d0507-ad21-4783-a83a-08d6d0f9e36e': ex90 as unknown as ExampleAction,
  'd9eb6be1-6185-4d6e-8459-08db738638c3': ex91 as unknown as ExampleAction,
  'dd277f4e-50a4-4971-26fc-08d697a0f29b': ex92 as unknown as ExampleAction,
  'dd32199e-8d36-465a-b13d-08dac77c5292': ex93 as unknown as ExampleAction,
  'e4ec073a-1f86-449c-8001-08da66cce8dc': ex94 as unknown as ExampleAction,
  'ea84295f-a89f-4eed-2181-08d87f35f7db': ex95 as unknown as ExampleAction,
  'ef1a10ef-bbb2-4dcf-5f17-08d6cebc3090': ex96 as unknown as ExampleAction,
  'efa8a4af-4a87-4d52-d718-08d827485760': ex97 as unknown as ExampleAction,
  'f28447de-e525-440e-5f9b-08d67b52833a': ex98 as unknown as ExampleAction,
  'f6fc9c05-7b95-40f7-b326-08d6756598a8': ex99 as unknown as ExampleAction,
  'f757e64d-dff9-4bc1-6b82-08da4f3f8574': ex100 as unknown as ExampleAction,
  'fa6ce878-59d6-4c9a-06b4-08db4d58400e': ex101 as unknown as ExampleAction,
  'fb351711-0941-4816-d9b7-08db2ba80230': ex102 as unknown as ExampleAction,
  'fe04a515-508b-4238-645d-08d8ba8b34b3': ex103 as unknown as ExampleAction,
  'ff3309da-7c30-4655-6b7d-08da4f3f8574': ex104 as unknown as ExampleAction,
};

export function getExampleAction(code: string): ExampleAction | null {
  const key = code.trim();
  if (!key) return null;
  return EXAMPLES[key] ?? EXAMPLES[key.toLowerCase()] ?? null;
}

export function listExampleActions(): ExampleAction[] {
  return Object.values(EXAMPLES);
}
